import 'package:khulasa/Models/source.dart';

List<NewsSource> sources = [
  NewsSource(
    source: 'Dawn News',
    sourceUrdu: 'ڈان نیوز',
    titleTag: 'story__link',
    contentTag: 'story__content',
    dateTag: 'story__time text-4',
    isDateTime: false,
    webLink: "https://www.dawnnews.tv/",
    rssSummaryRatio: 0.1,
  ),
  // Source(
  //   source: 'ARY News',
  //   titleTag: 'tdb-title-text',
  //   contentTag: 'p',
  //   dateTag: 'time',
  //   dateTagType: 'attribute-tag',
  //   webLink: "https://urdu.arynews.tv/",
  //   rssSummaryRatio: 0.2,
  //   attributeName: 'datetime',
  // ),
  NewsSource(
    source: 'Jang',
    sourceUrdu: 'جنگ',
    titleTag: 'h1',
    titleTagType: 'tag',
    contentTag: 'detail_view_content',
    contentTagType: 'paragraph',
    dateTag: 'detail-time',
    dateIndex: 2,
    isDateTime: false,
    webLink: "https://jang.com.pk/",
    rssSummaryRatio: 0.1,
  ),
  NewsSource(
    source: 'Express News',
    sourceUrdu: 'ایکسپریس نیوز',
    titleTag: 'title',
    contentTag: 'p',
    contentTagType: 'paragraph',
    dateTag: 'timestamp',
    dateTagType: 'attribute-class',
    isDateTime: false,
    attributeName: 'title',
    webLink: 'https://www.express.pk/',
    rssSummaryRatio: 0.1,
  ),
  // Source(
  //   source: 'Nawaiwaqt',
  //   titleTag: 'h2',
  //   titleTagType: 'tag',
  //   contentTag: 'entry-post mrgn-top',
  //   dateTag: 'time',
  //   isDateTime: false,
  //   webLink: 'https://www.nawaiwaqt.com.pk/home',
  //   rssSummaryRatio: 0.3,
  // ),
  NewsSource(
    source: 'Jasarat',
    sourceUrdu: 'جسارت',
    titleTag: 'entry-title',
    contentTag: 'p',
    contentTagType: 'paragraph',
    dateTag: 'time',
    dateTagType: 'attribute-tag',
    attributeName: 'datetime',
    webLink: 'https://www.jasarat.com/',
    rssSummaryRatio: 0.2,
  ),
  NewsSource(
    source: 'BBC Urdu',
    sourceUrdu: 'بی بی سی',
    titleTag: 'bbc-1gvq3vt e1p3vdyi0',
    contentTag: 'p',
    contentTagType: 'paragraph',
    dateTag: 'time',
    dateTagType: 'attribute-tag',
    attributeName: 'datetime',
    webLink: 'https://www.bbc.com/urdu',
    rssSummaryRatio: 0.05,
  ),
];
