import 'package:khulasa/Models/source.dart';

List<Source> sources = [
  Source(
    source: 'Dawn News',
    titleTag: 'story__link',
    contentTag: 'story__content',
    dateTag: 'story__time text-4',
    webLink: "https://www.dawnnews.tv/",
    rssSummaryRatio: 0.1,
  ),
  Source(
    source: 'ARY News',
    titleTag: 'tdb-title-text',
    contentTag: 'p',
    dateTag: 'time',
    dateTagType: 'attribute-tag',
    webLink: "https://urdu.arynews.tv/",
    rssSummaryRatio: 0.2,
    attributeName: 'datetime',
  ),
  Source(
    source: 'Jang',
    titleTag: 'h1',
    titleTagType: 'tag',
    contentTag: 'p',
    dateTag: 'detail-time',
    dateTagType: 'temp-noDate',
    webLink: "https://jang.com.pk/",
    rssSummaryRatio: 0.1,
  ),
  Source(
    source: 'Express News',
    titleTag: 'title',
    contentTag: 'p',
    dateTag: 'timestamp',
    dateTagType: 'temp-noDate', //'attribute-class',
    attributeName: 'title',
    webLink: 'https://www.express.pk/',
    rssSummaryRatio: 0.1,
  ),
  // Source(
  //   source: 'Nawaiwaqt',
  //   titleTag: 'h2',
  //   titleTagType: 'tag',
  //   contentTag: 'p',
  //   dateTag: 'attribute-class',
  //   dateTagType: 'temp-noDate',
  //   attributeName: 'title',
  //   webLink: 'https://www.nawaiwaqt.com.pk/latest',
  //   rssSummaryRatio: 0.1,
  // ),
];
